name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    - name: App Center
      uses: lukabanjac/AppCenter-Github-Action@v1.3.3
      with:
        appName: lukabanjac/RN-Test
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Testers
        file: app/build/outputs/apk/release/app-release-unsigned.apk
        notifyTesters: true
        debug: false
