name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - alpha
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          yarn install
      - name: Run CI with Lefthook
        run: |
          yarn lefthook run ci-hook
      - name: Run test
        run: |
          yarn test-ci

name: Continuous Delivery

on:
  push:
    branches:
      - main

  jobs:
    deploy:
      - name: App Center
        uses: lukabanjac/AppCenter-Github-Action@v1.3.3
        with:
          appName: lukabanjac/RN-Test
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk
          notifyTesters: true
          debug: false
